### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

### ISSUE THREAD

**Issue by Liamkk** [ebranlard/wtDigiTwin#3]
Hello
When I run the example file "301_Kalman_2DOF_5States" and "300_Kalman_2DOF_7States", the process abort.
The run output showes that:

Time step        0 t=     0.000  WS= 7.9 Thrust=401615.5
Time step      500 t=    25.000  WS= 7.8 Thrust=366735.2
Traceback (most recent call last):
  File "E:/DeskStudy/CGN/wtDigiTwin/wtDigiTwin-1.0/examples/onshore_OFLin/301_Kalman_2DOF_5States.py", line 105, in <module>
    KF= KalmanFilterTNLinSim(KM, FstFile, MeasFile, OutputFile, base, StateFile, nUnderSamp, tRange, bFilterAcc, nFilt, NoiseRFactor, sigX, sigY, bExport)
  File "e:\deskstudy\cgn\wtdigitwin\wtdigitwin-1.0\welib\welib\kalman\TNLin.py", line 467, in KalmanFilterTNLinSim
    KF.moments()
  File "e:\deskstudy\cgn\wtdigitwin\wtdigitwin-1.0\welib\welib\kalman\TNLin.py", line 239, in moments
    z_test = fastlib.ED_TwrGag(WT.ED) - WT.ED['TowerBsHt']
TypeError: unsupported operand type(s) for -: 'tuple' and 'int'
[TIME] Simulation Loop                Elapsed:  1.97s

**Comment by Liamkk** [comment]
Change the code in TNLin.py, line 239 and line 411
z_test = list(fastlib.ED_TwrGag(KF.WT.ED)[-1] - KF.WT.ED['TowerBsHt'])

The issue is closed.

**Comment by Liamkk** [comment]
Change the code in TNLin.py, line 239 and line 411
z_test = list(fastlib.ED_TwrGag(KF.WT.ED)[-1] - KF.WT.ED['TowerBsHt'])

The issue is closed.

**Comment by ebranlard** [comment]
Hi, 

Thanks for reporting this. In fact, you would need to ensure the TwrGag is a numpy array instead of a list. You can do this with `np.asarray`. Feel free to submit a pull request.
